### ISSUE TITLE
Create camel JAX-RS example

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-swarm/wildfly-swarm-camel#8]
Demonstrate:

* camel-core REST DSL
* camel-cxf
* Interaction with swarm JAX-RS fraction

**Comment by tdiesler** [comment]
examples branch pushed upstream https://github.com/wildfly-swarm/wildfly-swarm-camel/tree/examples

**Comment by tdiesler** [comment]
https://issues.jboss.org/browse/SWARM-427
